spring:
  application:
    name: ecommerce-service

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

    hikari:
      data-source-properties:
        prepareThreshold: 0
      max-lifetime: 1800000       # 30 minutes
      idle-timeout: 600000        # 10 minutes
      minimum-idle: 2
      maximum-pool-size: 10       # Increase slightly if needed
      pool-name: HikariCP
      allowPoolSuspension: false
      keepalive-time: 0

  jpa:
    hibernate:
      ddl-auto: none            # Flyway manages schema/tables
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    locations: classpath:db/migration
    schemas:
      - auth_service
      - product_service
    default-schema: auth_service        # use one schema for Flyway metadata table
    create-schemas: true
    table: flyway_schema_history        # make sure history table name is consistent

server:
  port: ${SERVER_PORT:8081}
