name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repo
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Build the Docker image
      - name: Build Docker image
        run: docker build -t my-backend .

      # 3. Push to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.GITHUB_TOKEN }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker image
        run: docker tag my-backend ghcr.io/${{ github.repository }}:latest && docker push ghcr.io/${{ github.repository }}:latest
